name: Check Filename Quality

on:
  push:
    branches:
      - 'feature/LAB-4_*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main' # Змінено на main для більшої сумісності з форками

jobs:
  check_filename:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clone checker script repository (Version 0.1.0)
      run: |
        git clone --depth 1 --branch 0.1.7 https://github.com/DilemmaFixer3/devops-tooling.git devops-tooling-checker

    - name: Run Filename Check Script
      run: |
        bash devops-tooling-checker/checker-scripts/check-filename.sh $PWD